{{--
    x-frontend.picture — Responsive optimised image component.

    Renders a <picture> with WebP srcset + JPEG/PNG fallback.
    WebP derivatives are expected at: {basename}-{width}.webp
    (generated by `php artisan images:optimize`).

    Props:
      src           - Absolute URL or asset path of the original image (JPEG/PNG).
      alt           - Alt text (required; use "" for decorative images).
      width         - Intrinsic display width in pixels (required).
      height        - Intrinsic display height in pixels (required).
      sizes         - <img sizes> attribute. Default: "100vw".
      loading       - "lazy" (default) | "eager".
      decoding      - "async" (default) | "sync" | "auto".
      fetchpriority - "high" | "low" | "auto" (default: not set).
      class         - CSS classes forwarded to <img>.
      imgAttributes - Additional HTML attributes merged onto <img>.
      webp-widths   - Comma-separated widths for srcset. Default: "400,800,1200".

    Usage — lazy image in a card:
        <x-frontend.picture
            :src="$animal->media->url()"
            :alt="$animal->name . ' — ' . $animal->breed"
            width="800"
            height="600"
            sizes="(max-width: 640px) 100vw, (max-width: 1024px) 50vw, 400px"
            class="animal-card__img"
        />

    Usage — LCP hero image:
        <x-frontend.picture
            src="https://images.unsplash.com/photo-xxx?auto=format&fit=crop&fm=webp"
            alt="Kot bengalski w naturalnym oświetleniu"
            width="1335"
            height="918"
            loading="eager"
            fetchpriority="high"
            sizes="100vw"
            class="hero__image"
        />
--}}

@props([
    'src',
    'alt'           => '',
    'width'         => null,
    'height'        => null,
    'sizes'         => '100vw',
    'loading'       => 'lazy',
    'decoding'      => 'async',
    'fetchpriority' => null,
    'class'         => '',
    'webpWidths'    => '400,800,1200',
])

@php
    $widths      = array_filter(array_map('intval', explode(',', $webpWidths)));
    $isUnsplash  = str_contains($src, 'unsplash.com');
    $isExternal  = str_starts_with($src, 'http') && ! $isUnsplash;
    $srcsetParts = [];

    if ($isUnsplash) {
        // Unsplash supports format conversion via URL params.
        // Strip any existing format/fm/w/q params and rebuild.
        $baseUrl = strtok($src, '?');
        foreach ($widths as $w) {
            $srcsetParts[] = $baseUrl . '?auto=format&fit=crop&fm=webp&w=' . $w . '&q=78 ' . $w . 'w';
        }
        // Fallback src: original format, reasonable width
        $fallbackSrc = $src;
    } elseif (! $isExternal) {
        // Local storage media — point to generated WebP derivatives.
        // src is expected to be a full URL like /storage/media/file.jpg
        // Derive path without extension.
        $parsedPath  = parse_url($src, PHP_URL_PATH);
        $info        = pathinfo($parsedPath);
        $dirUrl      = rtrim($info['dirname'], '/');
        $basename    = $info['filename'];

        $relDir = ltrim($dirUrl, '/');
        $mediaSubDir = preg_replace('#^storage/?#', '', $relDir);

        foreach ($widths as $w) {
            $webpUrl = asset($relDir . '/' . $basename . '-' . $w . '.webp');
            // Check existence either in public/storage or storage/app/public
            $publicPath  = public_path($relDir . '/' . $basename . '-' . $w . '.webp');
            $storagePath = storage_path('app/public/' . $mediaSubDir . '/' . $basename . '-' . $w . '.webp');
            if (file_exists($publicPath) || file_exists($storagePath)) {
                $srcsetParts[] = $webpUrl . ' ' . $w . 'w';
            }
        }
        $fallbackSrc = $src;
    } else {
        // Fully external — no WebP srcset available; render plain <img>.
        $fallbackSrc = $src;
    }

    $hasSrcset = ! empty($srcsetParts);
    $srcsetStr = implode(', ', $srcsetParts);
@endphp

@if($hasSrcset)
<picture>
    <source
        type="image/webp"
        srcset="{{ $srcsetStr }}"
        @if($sizes) sizes="{{ $sizes }}" @endif
    >
    <img
        src="{{ $fallbackSrc }}"
        alt="{{ $alt }}"
        @if($width)  width="{{ $width }}"   @endif
        @if($height) height="{{ $height }}" @endif
        loading="{{ $loading }}"
        decoding="{{ $decoding }}"
        @if($fetchpriority) fetchpriority="{{ $fetchpriority }}" @endif
        @if($sizes) sizes="{{ $sizes }}" @endif
        @if($class)  class="{{ $class }}"   @endif
        {{ $attributes }}
    >
</picture>
@else
<img
    src="{{ $fallbackSrc }}"
    alt="{{ $alt }}"
    @if($width)  width="{{ $width }}"   @endif
    @if($height) height="{{ $height }}" @endif
    loading="{{ $loading }}"
    decoding="{{ $decoding }}"
    @if($fetchpriority) fetchpriority="{{ $fetchpriority }}" @endif
    @if($sizes)  sizes="{{ $sizes }}"   @endif
    @if($class)  class="{{ $class }}"   @endif
    {{ $attributes }}
>
@endif
